apiVersion: v1
kind: Service
metadata: 
  name: cs-mongodb-clusterip
spec:
  type: ClusterIP
  selector:
    app: cs-mongodb
  ports:
    - name: cs-mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: cs-mongodb-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: cs-mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017