apiVersion: v1
kind: Service
metadata: 
  name: checkinservice-clusterip
spec:
  type: ClusterIP
  selector:
    app: checkinservice
  ports:
  - name: checkinservice
    protocol: TCP
    port: 80
    targetPort: 80