apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bs-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bs-postgres
  template:
    metadata:
      labels:
        app: bs-postgres
    spec:
      containers:
        - name: bs-postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "postgresdb"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bs-postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: bookingservice-pvc
