apiVersion: v1
kind: Service
metadata: 
  name: bookingservice-clusterip
spec:
  type: ClusterIP
  selector:
    app: bookingservice
  ports:
  - name: bookingservice
    protocol: TCP
    port: 80
    targetPort: 80
  - name: bookinggrpcservice
    protocol: TCP
    port: 5947
    targetPort: 5947