apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-mssql-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: fs-mssql
  template:
    metadata:
      labels:
        app: fs-mssql
    spec:
      containers:
        - name: fs-mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fs-mssql-secret
                  key: SA_PASSWORD
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: mssqldb
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: flightservice-pvc
